CREATE TABLE USER(
	ID   INT IDENTITY (1,1) NOT NULL,
   	USERNAME VARCHAR (32) NOT NULL,
   	PASSWORD VARCHAR (32) NOT NULL,
   	EMAIL    VARCHAR (32) NOT NULL,
   	LICENSE  VARCHAR (32) NOT NULL,
   	PAYMENTINFO VARCHAR (32) NOT NULL,
   	LOGGEDIN BOOLEAN NOT NULL, 
   	PRIMARY KEY (ID)
);